apiVersion: v1
kind: Pod
metadata:
  name: eventstore
spec: 
  restartPolicy: Always
  containers:
  - name: eventstore
    image: "wkruse/eventstore"
    command: ["./run-node.sh","--ext-ip=0.0.0.0","--http-prefixes=http://*:2113/","--run-projections=all"]
    
#    ,"--http-prefixes=\"http://*:2113/\""
    