apiVersion: v1
kind: Service
metadata:
  name: eventstore
  labels:
    component: eventstore
spec:
  type: LoadBalancer
  clusterIP: None
  selector:
    component: eventstore
  ports:
  - name: http
    port: 2113
    protocol: TCP
  - name: http3
    port: 2112
    protocol: TCP
  - name: http2
    port: 1112
    protocol: TCP
  - name: transport
    port: 1113
    protocol: TCP
